#!/bin/bash

if [ -e /tmp/profiles.xml ] ;then rm -r /tmp/profiles.xml
fi

if [ -e /tmp/JCLicenseCheck.txt ] ;then rm -r /tmp/JCLicenseCheck.txt
fi

touch /tmp/JCLicenseCheck.txt
JCLicenseResults="/tmp/JCLicenseCheck.txt"
sudo profiles show -output /tmp/profiles.xml stdout-xml	> /dev/null

connectLicenseInstalled=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.plist LicenseFile)
connectLoginLicenseInstalled=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.login.plist LicenseFile)
profilesWithConnectLicense=$(grep -A 1 "LicenseFile" /tmp/profiles.xml | awk -F'<string>' '{print $2}' | sed 's/string>//g' | sed 's/<.*//;/^$/d')

connectDateCompare=$(date +%Y%m%d)



#CHECK FOR JAMF CONNECT LICENSE, THEN COPY AND CONVERT TO A READABLE FORMAT
LicensefromLogin=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.login.plist LicenseFile 2>/dev/null)
LicensefromMenubar=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.plist LicenseFile 2>/dev/null)
if [[ "$LicensefromLogin" == "PD94"* ]]; then
	(echo "$LicensefromLogin" | base64 -d) > /tmp/license.txt
elif [[ "$LicensefromMenubar" == "PD94"* ]]; then
	(echo "$LicensefromMenubar" | base64 -d) > /tmp/license.txt
else
	file=""
fi

#Variable for License Check
connectLicenseExpiration=$(grep -A 1 "ExpirationDate" /tmp/license.txt | awk '{ print $1 }' | sed 's/<string>//g' | sed 's/<.*//;/^$/d' | tr -d "-")

case "$connectLoginLicenseInstalled" in
	"")
		echo -e "No Connect Login License Found\n"
	;;
	*)
		for i in $profilesWithConnectLicense; do
			if [[ "$i" == "$connectLoginLicenseInstalled" ]]; then
				if [ $connectDateCompare -ge $connectLicenseExpiration ]; then
					echo -e "Matching Profile found for installed Connect License (com.jamf.connect.login). Currently installed Jamf Connect License is expired\n Expired License is:\n $i\n\n" >> $JCLicenseResults
				else
					echo -e "Matching Profile found for installed Connect License (com.jamf.connect.login). Currently installed Jamf Connect License is Valid\n. License is:\n $i\n\n" >> $JCLicenseResults
				fi
			else
				echo -e "Mismatch between installed Connect license found in com.jamf.connect.login plist and an installed profile. Search the profiles.xml file for this license string to see which one profile is attempting to install this license string: $i\n\n" >> $JCLicenseResults
			fi
		done
	;;
esac

case "$connectLicenseInstalled" in
	"")
		echo "No Connect Login License Found\n" >> $JCLicenseResults
	;;
	*)
		for i in $profilesWithConnectLicense; do
			if [[ "$i" == "$connectLicenseInstalled" ]]; then
				if [ $connectDateCompare -ge "$connectLicenseExpiration" ]; then
					echo -e "Matching Profile found for installed Connect License (com.jamf.connect). Currently installed Jamf Connect License is expired\n Expired License is:\n $i\n\n" >> $JCLicenseResults
				else
					echo -e "Matching Profile found for installed Connect License (com.jamf.connect). Currently installed Jamf Connect License is Valid.\n License is:\n $i\n\n" >> $JCLicenseResults
				fi
			else
				echo -e "Mismatch between installed Connect license found in com.jamf.connect plist and an installed profile. Search the profiles.xml file for this license string to see which one profile is attempting to install this license string: $i\n\n" >> $JCLicenseResults
			fi
		done
	;;
esac

jamfHelperReadResults=$(cat $JCLicenseResults)

/Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -description "$jamfHelperReadResults" -button1 "Dismiss" -title "Jamf Connect License Checker" -heading "Reference files stored in /tmp" -windowType utility -defaultButton 1
