#!/bin/bash

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#        * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#      * Redistributions in binary form must reproduce the above copyright
#           notice, this list of conditions and the following disclaimer in the
#           documentation and/or other materials provided with the distribution.
#         * Neither the name of the JAMF Software, LLC nor the
#           names of its contributors may be used to endorse or promote products
#           derived from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED BY JAMF SOFTWARE, LLC "AS IS" AND ANY
# EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL JAMF SOFTWARE, LLC BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ENABLE AUTHCHANGER TO USE THE BUILT IN PAM FEATURE FOR COM.JAMF.CONNECT.LOGIN
#THIS IS OKTA SPECIFIC, NOT SUPPORTED ON OTHER IDPS AS OF 8/11/23

/usr/local/bin/authchanger -DefaultJCRight

#THIS WORKFLOW SHOULD BE THOROUGHLY TESTED PRIOR TO DEPLOYMENT. IT CAN THOROUGHLY MESS UP YOUR SUDO PERMISSIONS IF YOU SEND IT OUT UNTESTED
#WILL REQUIRE SUDO PERMISSIONS TO RUN. 

setPamToRequired=("# sudo: auth account password session
	auth       required       pam_saml.so
	# auth       sufficient     pam_smartcard.so
	# auth       required       pam_opendirectory.so
	account    required       pam_permit.so
	password   required       pam_deny.so
	session    required       pam_permit.so")

setPamToEnabled=("# sudo: auth account password session
	auth       sufficient     pam_saml.so
	auth       sufficient     pam_smartcard.so
	auth       required       pam_opendirectory.so
	account    required       pam_permit.so
	password   required       pam_deny.so
	session    required       pam_permit.so")

setPamToDefault=("# sudo: auth account password session
	auth       sufficient     pam_smartcard.so
	auth       required       pam_opendirectory.so
	account    required       pam_permit.so
	password   required       pam_deny.so
	session    required       pam_permit.so")

#DECLARE PAM SETTING FOR SCRIPT TO SET, OPTIONS ARE 'DEFAULT' 'ENABLED' OR 'REQUIRED'
#THIS IS THE ONE AND ONLY VARIABLE YOU NEED TO SET FOR THIS SCRIPT. EVERYTHING ELSE SHOULD BE STATIC
pamSetting="DEFAULT"

if [[ $pamSetting == DEFAULT ]]; then
	echo "$setPamToDefault" > /etc/pam.d/sudo
elif [[ $pamSetting == ENABLED ]]; then
	echo "$setPamToEnabled" > /etc/pam.d/sudo
elif [[ $pamSetting == REQUIRED ]]; then
	echo "$setPamToRequired" > /etc/pam.d/sudo
else
	echo "Invalid PAM setting, exiting"
fi
